name: make a mesa
on:
   workflow_dispatch:
jobs:
  job-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: download archives
        run: |
          sudo apt-get install git wget
      - name: get termux-docker
        run: |
          git clone https://github.com/termux/termux-docker.git
          cd termux-docker
          docker run hello-word
