name: Build Mesa for ARM Cross-Compile

on:
  push:
    branches:
      - Panfrost-G610
  pull_request:
    branches:
      - Panfrost-G610

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt-get update
          sudo apt build-dep mesa -y
          pip3 install mako

      - name: Clone and build libdrm for armv7
        run: |
          git clone --depth 1 https://gitlab.freedesktop.org/mesa/drm.git
          cd drm
          meson setup "build-armv7" \
            --prefix=/opt/libdrm/32 \
            --cross-file "../armv7_cross_file.txt" \
            -Ddefault_library=static \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=disabled \
            -Dvc4=disabled \
            -Detnaviv=disabled
          ninja -C "build-armv7"
          sudo ninja -C "build-armv7" install

      - name: Clone and build libdrm for aarch64
        run: |
          cd drm
          meson setup "build-aarch64" \
            --prefix=/opt/libdrm/64 \
            --cross-file "../aarch64_cross_file.txt" \
            -Ddefault_library=static \
            -Dintel=disabled \
            -Dradeon=disabled \
            -Damdgpu=disabled \
            -Dnouveau=disabled \
            -Dvmwgfx=disabled \
            -Dfreedreno=disabled \
            -Dvc4=disabled \
            -Detnaviv=disabled
          ninja -C "build-aarch64"
          sudo ninja -C "build-aarch64" install

      - name: Create build directory for armv7
        run: mkdir -p build/armv7

      - name: Configure armv7 build
        run: |
          cd build/armv7
          CFLAGS="-O3" meson setup --cross-file ../../armv7_cross_file.txt \
            -Dgallium-drivers=panfrost,swrast \
            -Dvulkan-drivers= \
            -Dbuildtype=release \
            -Dllvm=disabled \
            -Dplatforms=x11 \
            -Dprefix=/opt/panfrost/32 ../..

      - name: Build and install armv7
        run: |
          cd build/armv7
          ninja
          sudo ninja install

      - name: Create build directory for aarch64
        run: mkdir -p build/aarch64

      - name: Configure aarch64 build
        run: |
          cd build/aarch64
          CFLAGS="-O3" meson setup --cross-file ../../aarch64_cross_file.txt \
            -Dgallium-drivers=panfrost,swrast \
            -Dvulkan-drivers= \
            -Dbuildtype=release \
            -Dllvm=disabled \
            -Dplatforms=x11 \
            -Dprefix=/opt/panfrost/64 ../..

      - name: Build and install aarch64
        run: |
          cd build/aarch64
          ninja
          sudo ninja install

      - name: Restructure output directories
        run: |
          # Cria a pasta glibc e move as bibliotecas dentro dela
          sudo mkdir -p /opt/panfrost/glibc
          sudo mv /opt/panfrost/64/lib/aarch64-linux-gnu /opt/panfrost/glibc/lib
          sudo mv /opt/panfrost/32/lib/arm-linux-gnueabihf /opt/panfrost/glibc/lib32

      - name: Cleanup intermediate directories
        run: |
          sudo rm -rf /opt/panfrost/64 /opt/panfrost/32

      - name: Compress the unified directory structure
        run: |
          cd /opt/panfrost
          tar -czvf mesa_output.tar.gz *

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mesa-unified-output
          path: /opt/panfrost/mesa_output.tar.gz
